# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84acb2f66a79cc6638531a68f13db50b4a822236d44e96529e74466c069f4d927a49e7afaa8bc2d4f5fd731fe35f8dadc62c216bf3851ae455d9752860851a58

test:
  secret_key_base: 085fa41d9b7c6d1d08916a2187f6d462b8527dfe61bc0bcd90f63929918c01beacdc2d5a89f4f5f0e4fcaf0dac0b11bb848534e061d2186a3ae87968e31469b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
